# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts --no-audit --no-fund

# Copy source
COPY . .

# Build TypeScript
RUN npm run build

# Default command
CMD ["node", "dist/index.js"]
